spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: auction_user
    password: auction_pass

  jpa:
    hibernate:
      ddl-auto: update
